[project]
name = "digistore24"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["django>=5.2.5", "django-rest-framework>=0.1.0"]

[dependency-groups]
dev = ["django-stubs>=5.2.2", "pytest>=8.4.1", "pytest-django>=4.11.1"]
